[package]
name = "a2vm-tui"
version = "0.1.0"
edition = "2021"

[features]
default = ["audio"]
audio = ["dep:rodio", "a2vm-oxide/audio"]

[dependencies]
a2vm-core = { workspace = true }
a2vm-oxide = { workspace = true, default-features = false }
clap = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
rodio = { workspace = true, optional = true }
log = { workspace = true }
env_logger = { workspace = true }
